/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f3xx.h>


void UART_INIT()
{
	RCC->CR |= RCC_CR_HSION; // HSI ON
	RCC->APB2ENR |= RCC_APB2ENR_USART1EN; //UART1 ON
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;


	USART1->BRR = 0x0341 ;         // 9600 ~9.6khz


	 //Alternating function, for TX (PA9)
	 GPIOA->MODER |= GPIO_MODER_MODER9_1 ;//10 - ALTERNATATIVE
	 GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR9_0 | GPIO_OSPEEDER_OSPEEDR9_1;     //Fast Speed
	 GPIOA->AFR[1] |= GPIO_AFRH_AFRH1 &(7U<<4);//0X0111 - AF7
	 GPIOA->OTYPER &= ~GPIO_OTYPER_OT_9 ;//PUSH PULL
	 GPIOA->PUPDR |= GPIO_PUPDR_PUPDR9_0;//PULL UP

	 //RX -PA10
	 GPIOA->MODER |= GPIO_MODER_MODER10_1;
	 GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR10_0 | GPIO_OSPEEDER_OSPEEDR10_1; //Fast Speed
	 GPIOA->AFR[1] |= GPIO_AFRH_AFRH2 & (7U<<8);//0X0111 - AF7


	 USART1->CR2 = 0;
	 USART1->CR3 = 0;

}
void UART_OPEN()
{
	USART1->CR1 = USART_CR1_UE;

}
void UART_READ()
{
	USART1->CR1 |= USART_CR1_RE;


}
void UART_WRITE()
{
	USART1->CR1 |= USART_CR1_TE ;

	while (1)
	  {
	      USART1->TDR = 0x0f;
	  }
}



void UART_CLOSE()
{
	USART1->CR1 = 0x0;


}
void UART_DEINIT()
{
	    RCC->CR &=0; // HSI OFF
		RCC->APB2ENR &= 0; //UART1 OFF
		RCC->AHBENR &= 0;//GPIOA OFF

		USART1->BRR = 0 ;         // 9600 ~9.6khz


		// TX (PA9)
		 GPIOA->MODER &= 0 ;
		 GPIOA->OSPEEDR &= 0;
		 GPIOA->AFR[1] &= 0;
		 GPIOA->OTYPER&= 0 ;
		 GPIOA->PUPDR &= 0;

		 //RX -PA10
		 GPIOA->MODER &= 0;
		 GPIOA->OSPEEDR &= 0;
		 GPIOA->AFR[1] &= 0;


		 USART1->CR2 = 0;
		 USART1->CR3 = 0;


}

int main(void)
{
	UART_INIT();
	UART_OPEN();
	UART_WRITE();
	UART_CLOSE();
	UART_DEINIT();


}
